# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-04 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('emp_no', models.IntegerField(primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
                ('first_name', models.CharField(max_length=14)),
                ('last_name', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('male', 'M'), ('female', 'F')], max_length=6)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
