# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-04 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept_emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='departments',
            name='dept_no',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='dept_emp',
            name='dept_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_no_by_departments', to='empapp.departments'),
        ),
        migrations.AddField(
            model_name='dept_emp',
            name='emp_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_no_by_employees', to='empapp.employees'),
        ),
    ]
