# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-04 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_auto_20191204_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='titles',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles_by_employees', to='empapp.employees')),
            ],
        ),
    ]
