# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-04 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='salaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries_by_employees', to='empapp.employees')),
            ],
        ),
    ]
